### ISSUE TITLE
producing dot files

### ISSUE THREAD

**Issue by sasa1977** [sasa1977/boundary#15]
A new mix task `boundary.visualize` (alternative suggestions are welcome) should be created which produces [graphviz dot files](https://www.graphviz.org/pdf/dotguide.pdf) visualizing the relationships between boundaries.

The changes should be done on top of the [sub-boundaries branch](https://github.com/sasa1977/boundary/tree/sub-boundaries). While the work on sub-boundaries is still not finished, the foundations are in place and relatively stable. In particular, the parent-child relationships are managed, and the mix task code can use the API of the `Boundary` module to get the list of all boundaries and figure out the boundaries at each level.

The general idea is to produce one dotfile per each non-empty boundary-level. For example, consider the following tree of boundaries:

```
BlogEngine
  |
  +----Repo
  |
  +----Articles
  |
  +----Accounts

BlogEngineWeb

BlogEngineApp
```

With the following deps:

- App depends on Web and context
- Web depends on context
- inside the context, Articles and Accounts depend on Repo, and Articles depends on Accounts

We should produce two files:

```dot
# app.dot
digraph {
  BlogEngineApp -> BlogEngine;
  BlogEngineApp -> BlogEngineWeb;
  BlogEngineWeb -> BlogEngine;

  label="blog_engine application";
  labelloc=top;
}

# BlogEngine.dot
digraph {
  Articles -> Accounts;
  Articles -> Repo;
  Accounts -> Repo;

  label="BlogEngine boundary";
  labelloc=top;
}
```

In every graph we should make a visual distinction between deps to siblings and other deps. All dependencies to non-siblings (e.g. a dependency to the parent boundary, or a dependency to a boundary from another app) should visually distinguish from dependencies to siblings (boundaries from the same app sharing the same parent). Example:

![image](https://user-images.githubusercontent.com/202498/78750204-1131dd00-7970-11ea-8b5d-a1a914aa2fb6.png)

Here we have a compile-time dependency to the non-sibling `Mix` boundary. Notice how the `Mix` boundary is drawn with a different color, and the dependencies to this boundaries are represented with the dashed line. Also note that a compile-time dependency is represented with a corresponding label.

**Comment by polmiro** [comment]
I started looking into this today, great spec!

**Comment by axelson** [comment]
I think this can be closed now.

**Comment by sasa1977** [comment]
Yeah, good catch, thanks!
