### ISSUE TITLE
Do not track deps explicitly

### ISSUE THREAD

**Issue by LostKobrakai** [sasa1977/boundary#18]
I've a context `MyApp.Admin`, which includes common admin helpers. For this one I'd like to simply allow any exports of other boundaries without explicitly listing them. Is there a way to do that?

**Comment by sasa1977** [comment]
I'm not sure I completely understand the problem. What do you mean by "allow any exports of other boundaries"? Could you explain in more details, maybe by providing a code sketch of how you'd do it manually today (i.e. with explicitly listing).

**Comment by LostKobrakai** [comment]
So I'm planing to use boundaries for each context I have in my app (because it's currently a mess of inter-dependencies in places), so each `MyApp.*` will be a boundary. But `MyApp.Admin` should be able to call all of those without needing to have them `use Boundary, deps: […, …, …, …, …, …]` listed.

**Comment by sasa1977** [comment]
Unfortunately, this is currently not possible. The only option you have is to make the admin boundary [ignored](https://hexdocs.pm/boundary/Boundary.html#module-ignored-boundaries), which means those modules won't be checked by boundary (i.e. they can call anyone, and anyone can call them).

What is the problem with listing all the deps explicitly? Is it the fact that there are too much of them?

In the sub-boundary branch I added a support for mass export. Basically, you can say something like `exports: [{Schemas, except: [Base]}, ...]`, and then all `Schemas.*` modules are exported, except for `Schemas.Base`.

We could support something similar for deps, although I'm not completely convinced it's a good idea.

**Comment by LostKobrakai** [comment]
It's mostly lazyness. I don't care if the admin has helpers using just a single boundary or any of them. I'm also fine with using ignored, bu the docs read like it would work only for calls to that boundary and not for the dependencies part.

**Comment by sasa1977** [comment]
The docs say

> When a boundary is ignored, all modules belonging to it can use any other module, and can be used by any other module.

So basically ignore allows you to exclude some part of your code from boundary checks.

**Comment by LostKobrakai** [comment]
So I can't read correctly :P I read this differently. This should solve my usecase, thanks.

**Comment by sasa1977** [comment]
Do note that it will also allow any other context to use `Admin`. I guess it would be nicer if you could say that deps are not checked, but incoming calls still are. Maybe we could add a support for that, e.g. by having `deps: :allow_all, exports: :allow_all`. So in the admin case you could do `deps: :allow_all, exports: []`, and now admin can call anyone, but no one can call into admin, unless its added as a dep.

WDYT?

**Comment by LostKobrakai** [comment]
Yeah, that's what I was looking for initially.

**Comment by sasa1977** [comment]
OK, I think this is a sensible proposal :-) I'll reopen this issue.

**Comment by sasa1977** [comment]
So, I've finally found some time to play with this, and here's the current proposal:

1. A new composite option, `:check` will be added, with the default being `check: [in: true, out: true]`.
2. When check.in is set to false, all inbound calls are allowed.
3. When check.out is set to false, all outgoing calls are allowed.
4. If both are set to false, it's effectively the same as current `ignore?: true` (which will be removed)

So in your concrete example, you'd do `use Boundary, check: [out: false]` in the admin boundary, which means that admin can call everything, but other boundaries still need to declare admin as an explicit dependency. Note that in this case admin can also use internal modules of other boundaries, and that implicit dependency cycles can occur if another boundary depends on admin.

This is basically a bit more refined ignore mechanism, where you can ignore just one direction (in or out), giving us a bit more flexibility to postpone some clean up for later. But ultimately I still consider it as a temporary fix. Ideally, each boundary would explicitly declare its deps and exports.

WDYT?

**Comment by LostKobrakai** [comment]
For my usecase this sounds like a good way to go. It for sure is better to have explicitness everywhere, but this does allow the user to decide the tradeoffs.

**Comment by axelson** [comment]
I've wanted something like this for test helper modules that I have in `test/support` as well and that sounds like a good solution :+1: 

Would we want a way to customize how it shows up in`mix boundary.visualize`? Or maybe it would be better to optionally skip a boundary when generating a visualization.

**Comment by sasa1977** [comment]
> I've wanted something like this for test helper modules that I have in `test/support` as well and that sounds like a good solution +1

You can already do this today with the `ignore?: true` option. That's how I'm handling test helpers myself.

> Would we want a way to customize how it shows up in`mix boundary.visualize`? Or maybe it would be better to optionally skip a boundary when generating a visualization.

Visualize would not display boundaries which are completely ignored (i.e. which have both checks set to false). Otherwise, if at leas one check is enabled, the boundary would be displayed, because it has some incoming or outgoing connections.

**Comment by sasa1977** [comment]
In case you want to give this a try, I've pushed the ongoing work to [this branch](https://github.com/sasa1977/boundary/tree/0.6.0-dev). There are some breaking changes/deprecations, so take a look at [the changelog](https://github.com/sasa1977/boundary/blob/0.6.0-dev/CHANGELOG.md#060).

**Comment by axelson** [comment]
>>  I've wanted something like this for test helper modules that I have in test/support as well and that sounds like a good solution +1
>
> You can already do this today with the ignore?: true option. That's how I'm handling test helpers myself.

I guess I'm hoping to not need to add `ignore?: true` in every test helper, but instead just on a single test helper top-level boundary module.

**Comment by sasa1977** [comment]
> I guess I'm hoping to not need to add `ignore?: true` in every test helper, but instead just on a single test helper top-level boundary module.

If you placed all the test helpers under the `MySystemTest` namespace, you'd need to do it in only one place.
