### ISSUE TITLE
Basic Phoenix Boundaries don't work

### ISSUE THREAD

**Issue by naramore** [sasa1977/boundary#22]
After updating to Boundary 0.5.0, I found that the basic usage of Phoenix boundaries doesn't work as outlined in the docs here: https://github.com/sasa1977/boundary#example

```elixir
defmodule MySystem do
  use Boundary, deps: [], exports: []
  # ...
end

defmodule MySystemWeb do
  use Boundary, deps: [MySystem], exports: [Endpoint]
  # ...
end

defmodule MySystem.Application do
  use Boundary, deps: [MySystem, MySystemWeb]
  # ...
end
```

The example results in the follow warning:

```
warning: MySystemWeb can't be listed as a dependency because it's not a sibling, an ancestor, or a top-level boundary
  lib/my_system.ex:12
```

I believe the culprit is in the logic of `Boundary.Checker.validate_dep_allowed/4`. Shouldn't it also validate a dep successfully if the to_boundary is top-level?  The error message seems to indicate this is the case. 

Thanks for your work on the library!

**Comment by sasa1977** [comment]
> Shouldn't it also validate a dep successfully if the to_boundary is top-level?

It should, but `MySystem.Application` is not a top-level boundary, instead it is treated as a sub-boundary of `MySystem`. This is a bug in readme. You need to include `top_level?: true` in `MySystem.Application` boundary definition.
