### ISSUE TITLE
Doesn't emit `forbidden call to {Module}` warnings.

### ISSUE THREAD

**Issue by Skoda091** [sasa1977/boundary#29]
## Environment

- Elixir 1.11.1 (compiled with Erlang/OTP 23)
- Operating system: macOS 10.15.7
- Codebase size: ~674k LOC

## Situation

I am trying to set up the boundary to work with my project at work.

What I have done:

1. Added `{:boundary, "~> 0.7.0", runtime: false}`
2. Included `:boundary` in compilers list in `mix.exs` which resulted with`compilers: [:boundary, :phoenix, :gettext] ++ Mix.compilers()`
2. Defined boundaries with `use Boundary, deps: [], exports: []` or `use Boundary, top_level?: true, deps: [], exports: []`, depends on the particular boundary

## Current behavior

The current result is that I can only receive `{Modulee} is not included in any boundary` warnings, but I am not able to receive `forbidden call to {Module}` warnings which is relevant.

## Expected behavior

I would expect to see `forbidden call to {Module}` warnings as well.

**Comment by sasa1977** [comment]
Could you try with Elixir 1.11.2? There was a bug in Elixir 1.11.0 and 1.11.1 which prevents boundary from working correctly.

**Comment by Skoda091** [comment]
> Could you try with Elixir 1.11.2? There was a bug in Elixir 1.11.0 and 1.11.1 which prevents boundary from working correctly.

Solved, work like a charm. Thanks a lot.
