### ISSUE TITLE
Can't depend on nested boundaries

### ISSUE THREAD

**Issue by sokolnickim** [sasa1977/boundary#34]
I have started using Boundary on my project and have hit a curious roadblock. After looking at the source, I'm thinking there is no way to tell Boundary to successfully check my particular combination.

I am using the Phoenix Context way of organizing my entities, and to model a filesystem I have a context named `MyApp.FileSystem` under which I have the modules and respective structs: `MyApp.FileSystem.File` and `MyApp.FileSystem.Directory`. In the web layer, to figure out how to display the contents of a particular URI, I pattern match on those two structs. The basic layout of the project is as follows:

```elixir
defmodule MyApp do
  use Boundary, exports: [FileSystem]
  # ...
end

defmodule MyApp.FileSystem do
  use Boundary, exports: [File, Directory]
  # ...
end

defmodule MyAppWeb do
  use Boundary, deps: [MyApp, MyApp.FileSystem]
  # ...
end

defmodule MyAppWeb.FileLive.ShowComponent do
  # ...
  def render(%MyApp.FileSystem.File{} = file), do: # ...
  def render(%MyApp.FileSystem.Directory{} = file), do: # ...
end
```

No matter where along the hierarchy (`MyAppWeb`, `MyAppWeb.FileLive` or `MyAppWeb.FileLive.ShowComponent`) I place a `use Boundary, deps: [MyApp.FileSystem]`, I get an error message:

```
MyApp.FileSystem can't be listed as a dependency because it's not a sibling, a parent, or a dep of some ancestor
```

It seems that because the modules are nested under more than one level, there is no way to use them outside of their own parent boundary. I understand that enforcing that the web boundary only call the first level exports of its dependencies is desirable, and I've refactored some of my code to adhere to that, but there is no clean way to do this to enable pattern matching on these structs. I could put all my entities under `MyApp.Schemas`, I know it's something you've advocated for in the past, but I prefer to keep them within their context.

Is there is a trick to make Boundary allow the above, or is this something that would need to be changed? Thanks!

**Comment by sasa1977** [comment]
> It seems that because the modules are nested under more than one level, there is no way to use them outside of their own parent boundary.

Yes, the current limitation is that a boundary can't export modules from its sub-boundaries (except the sub-boundary root module). This is by design, but I agree that this limitation is too rigid. I've actually received a similar report a while ago.

The solution would be to allow exporting exported sub-boundary modules. That way you could do:

```elixir
defmodule MyApp do
  use Boundary, exports: [FileSystem, FileSystem.File, FileSystem.Directory]
  # ...
end
```

In addition, we could also support exporting the entire sub-boundary e.g. as

```elixir
use Boundary, exports: [{:boundary, FileSystem}]
```

Which would export all the exports of the `FileSystem` sub-boundary (plus the `FileSystem` module).

This is on my todo list, but I can't commit on a deadline. If you or someone else wants to try it, let me know and I can provide some pointers.

Until the fix arrives, a possible workaround is to [mark all sub-boundaries as top-level](https://hexdocs.pm/boundary/Boundary.html#module-promoting-boundaries-to-top-level). However, this will mean that you'll need to repeat the `deps` section in multiple boundaries (in this example `MyApp`, `MyApp.FileSystem`, ...).

**Comment by sokolnickim** [comment]
Thank you for the suggested workaround, it's much better than my solution of just disabling the checks entirely on the web layer. I don't mind keeping it as is and waiting for a fix, Boundary already provides me with plenty of value.

I would like to help, but I feel the design of the solution needs some careful consideration, and I'm not sure I'm qualified to make that call. For example, my intuition would have been instead to just allow to put sub-boundaries in the `deps` for external boundaries (the way it works now with the workaround, i.e. 
```elixir
defmodule MyAppWeb do
  use Boundary, deps: [MyApp, MyApp.FileSystem]
  # ...
```
without treating them as top-level when used within the parent boundary. Alternatively, I would have also thought about controlling whether an export is recursive, which I think would be similar to your second example:
```elixir
use Boundary, exports: [{:recursive, FileSystem}]
```

In any case, thank you for your work, I got stuck in a mess of circular dependencies and Boundary let me untangle all of it in a couple of days!

**Comment by randycoulman** [comment]
@sasa1977 I'd like to see if I can also tackle the second part of this: supporting `use Boundary, exports: [{:boundary, FileSystem}]`. I haven't yet looked into what this will take, but will do so when I can. If you have any guidance to get me started, that'd be great. If not, I'll figure out what I can and then ask more specific questions when I have them. Thanks!

**Comment by sasa1977** [comment]
FYI I've just pushed this as a part of version 0.9.0 to hex.
