### ISSUE TITLE
Boundary.Mix.Xref RuntimeError

### ISSUE THREAD

**Issue by aptinio** [sasa1977/boundary#41]
Here's a minimum example to reproduce this issue:
https://github.com/aptinio/boundary-mix-xref-error

### Steps to reproduce:
1. run `mix clean`
2. run `mix foo.ci`
3. run `mix foo.ci` again

### Expected result

CI result is consistent between runs.

### Actual result

Succeeding `mix foo.ci` runs fail with:

```
07:47:57.271 [error] GenServer Boundary.Mix.Xref terminating
** (RuntimeError) attempted to cast GenServer Boundary.Mix.Xref but no handle_cast/2 clause was provided
    (boundary 0.8.0) lib/gen_server.ex:819: Boundary.Mix.Xref.handle_cast/2
    (stdlib 3.16.1) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.16.1) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:remote_dispatch, Ecto.Changeset, :runtime}}
State: %{}
** (EXIT from #PID<0.94.0>) an exception was raised:
    ** (RuntimeError) attempted to cast GenServer Boundary.Mix.Xref but no handle_cast/2 clause was provided
        (boundary 0.8.0) lib/gen_server.ex:819: Boundary.Mix.Xref.handle_cast/2
        (stdlib 3.16.1) gen_server.erl:695: :gen_server.try_dispatch/4
        (stdlib 3.16.1) gen_server.erl:771: :gen_server.handle_msg/6
        (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

mix ecto.rollback --all took 0.7 seconds
CI checks took 3.9 seconds
** (Mix) mix ecto.rollback --all exited with status 1
```

### Notes

1. removing [`mix("ecto.rollback --all")`](https://github.com/aptinio/boundary-mix-xref-error/blob/main/lib/mix/foo/ci.ex#L18) from `lib/mix/foo/ci.ex` stops the error from happening
2. removing `--force` from [`mix("compile --force --warnings-as-errors")`](https://github.com/aptinio/boundary-mix-xref-error/blob/main/lib/mix/foo/ci.ex#L14) stops the error from happening

### Workaround

Replace

```elixir
[
  mix("compile --force --warnings-as-errors"),
  # ...
]
```

with

```elixir
[
  mix("clean"),
  mix("compile --warnings-as-errors"),
  # ...
]
```

I only found this workaround and the things that stop the error from happening while creating the minimal repo, but went ahead with filing this issue in the hopes that it'll be somewhat helpful.

**Comment by sasa1977** [comment]
Thanks for the report! 

With the help of @josevalim I produced the fix. It's currently in the [fix-lexical-tracker-issues branch](https://github.com/sasa1977/boundary/tree/fix-lexical-tracker-issues) if you want to give it a try.

**Comment by aptinio** [comment]
That fixes the issue in both the minimum repo and the actual repo I found the issue in. Thank you so much! <3

**Comment by sasa1977** [comment]
Thanks! The fix is now merged to master, and I plan to prepare the hex release soon.

**Comment by sasa1977** [comment]
Pushed 0.9.0 to hex
