### ISSUE TITLE
Upgrading boundary without clearing build results in a compilation error

### ISSUE THREAD

**Issue by axelson** [sasa1977/boundary#45]
I haven't been able to reproduce this yet but I wanted to file an initial bug report anyway. It seems that if you have a project with boundary 0.8.0 setup and compiled, then you upgrade that project to boundary 0.9.0 **without** clearing `_build` you will encounter a compilation warning.

A simple test of upgrading from 0.8.0 to 0.9.0 was unable to reproduce the error. Unfortunately I don't have the error message handy. If I am able to reproduce it I will add it. My guess is there's some sort of issue with the manifest.

**Comment by Nezteb** [comment]
@axelson Out of curiosity, what was the compilation error?

**Comment by axelson** [comment]
Unfortunately I didn't record that anywhere, and I haven't re-encountered it so it seems best to close this issue unless it re-occurs.
