### ISSUE TITLE
Parent boundary can override sub-boundary exports

### ISSUE THREAD

**Issue by stefanluptak** [sasa1977/boundary#47]
Hi again :-)

Situation:
```elixir
defmodule MySystem do
  use Boundary, exports: [Schemas, {Schemas, except: []}]

  defmodule Schemas do
    use Boundary, exports: [Visible]

    defmodule Visible do
      def hello, do: "world"
    end

    defmodule Hidden do
      def hello, do: "world"
    end
  end
end

defmodule MySystemWeb do
  use Boundary, deps: [MySystem]

  def hello do
    MySystem.Schemas.Visible.hello()
    MySystem.Schemas.Hidden.hello()
  end
end
```

When I run `mix compile` I get no warnings. I would assume, that `MySystemWeb` can't call `MySystem.Schemas.Hidden` since it's not exported by the `MySystem.Schemas` boundary.

Of course, I can do `exports: [{Schemas, except: [Hidden]}]` in the `MySystem` boundary definition, but that seems to be redundant and error-prone.

I am not sure if this is a bug or a design decision, but I think a parent boundary should not be able to export a sub-boundary module that was not exported by the sub-boundary itself. 🙂

**Comment by sasa1977** [comment]
> I think a parent boundary should not be able to export a sub-boundary module that was not exported by the sub-boundary itself

Yes, and it is supposed to work like that. See e.g. [this test](https://github.com/sasa1977/boundary/blob/0.9.1/test/mix/tasks/compile/boundary_test.exs#L800-L816). 

However, it looks like we don't perform the same checks with bulk exports, so this is a bug.

**Comment by sasa1977** [comment]
Pushed the fix to master, let me know if it works.

**Comment by stefanluptak** [comment]
> Pushed the fix to master, let me know if it works.

It's working. Thanks a lot. :-)
