### ISSUE TITLE
unknown boundary is listed as a dependency

### ISSUE THREAD

**Issue by floodico** [sasa1977/boundary#48]
why do i get this warning?
https://github.com/sasa1977/boundary/blob/1d8282311e2a43da4265cd5bbe2b8ac679a5da47/lib/boundary/mix/tasks/compile/boundary.ex#L232

**Comment by sasa1977** [comment]
This warning happens if boundary you listed as a dependency is not a boundary. E.g. suppose you have:

```elixir
defmodule Foo do
  use Boundary, deps: [Bar]
  # ...
end

defmodule Bar do
  # ...
end
```

Here the problem is that `Bar` is not a boundary. Here the solution would be to add `use Boundary` to `Bar`, or in other words to turn `Bar` into a boundary.

**Comment by floodico** [comment]
Thank you for your quick response:) 
Okay, but it's ready. 
And even more, you can see the result of `Boundary.view(:bar)`

```
%{
  classifier: %{
    boundaries: %{
      ### ... Core, DB 
      
      Bar => %{
        ancestors: [],
        app: :bar,
        check: %{
          aliases: false,
          apps: [core: :compile, core: :runtime, db: :compile, db: :runtime],
          in: true,
          out: true
        },
        deps: [{DB, :runtime}, {Core, :runtime}],
        errors: [],
        exports: [],
        file: "...",
        implicit?: false,
        line: 4,
        modules: [],
        name: Bar
        type: :relaxed
      }
    },
    modules: %{
      ### ...
    }
  },
  external_deps: #MapSet<[Core, DB]>,
  main_app: :bar,
  module_to_app: %{
    ###...
  },
  unclassified_modules: #MapSet<[]>,
  version: "0.9.0"
}
```

**Comment by floodico** [comment]
My bad, i had a dependency confusion i umbrella app. 
Thank you;)
