### ISSUE TITLE
Compilation error in VSCode when when using ElixirLS

### ISSUE THREAD

**Issue by martinthenth** [sasa1977/boundary#51]
Hi! I'm encountering an error in VSCode that breaks the internal compilation in ElixirLS. I tested this problem with Elixir version `1.13.4` and `1.14`. I use VSCode version `1.71.2` and ElixirLS version `v0.11.0` (both are the most recent versions). It happens for both non-umbrella and umbrella.

Steps to reproduce:

1. Have a working project
2. Set up `boundary`
3. Cause an error in the code (e.g. use a non-existing variable, or misspell a function)
4. See an error in `mix.exs` file (error is below)
5. See error detection in VSCode break (i.e. VSCode stops displaying where errors and unused functions are)

This is the error:

```elixir
** (KeyError) key :app not found in: [aliases: [], build_embedded: false, build_per_environment: true, build_scm: Mix.SCM.Path, config_path: "config/config.exs", consolidate_protocols: true, default_task: "run", deps: [], deps_path: "deps", elixirc_paths: ["lib"], erlc_paths: ["src"], erlc_include_path: "include", erlc_options: [], lockfile: "mix.lock", preferred_cli_env: [], start_permanent: false]
    (elixir 1.13.4) lib/keyword.ex:559: Keyword.fetch!/2
    (boundary 0.9.3) lib/boundary/mix/xref.ex:123: Boundary.Mix.Xref.seen_table/0
    (boundary 0.9.3) lib/boundary/mix/xref.ex:34: Boundary.Mix.Xref.initialize_module/1
    (boundary 0.9.3) lib/boundary/mix/tasks/compile/boundary.ex:128: Mix.Tasks.Compile.Boundary.record/5
    (elixir 1.13.4) src/elixir_env.erl:32: :elixir_env."-trace/2-lc$^0/1-0-"/3
    (elixir 1.13.4) src/elixir_env.erl:32: :elixir_env.trace/2
    (elixir 1.13.4) src/elixir_dispatch.erl:163: :elixir_dispatch.do_expand_import/7
    (elixir 1.13.4) src/elixir_dispatch.erl:92: :elixir_dispatch.dispatch_import/6
ElixirLS
```

I think the error is related to this change: https://github.com/sasa1977/boundary/commit/704b26b17a2f924dd47766186aa4e9900f2541c4, because it adds the config lookup for `app_name`

**Comment by sasa1977** [comment]
This should be fixed with next ElixirLS release. See https://github.com/elixir-lsp/elixir-ls/issues/717.
