### ISSUE TITLE
Getting unclassified module error for module which created by Mox

### ISSUE THREAD

**Issue by YasirAsar** [sasa1977/boundary#52]
Before going into the actual issue, I want to say "Thanks for the wonderful library!!"

The issue, I'm getting is with the `unclassified module`. While running `mix compile` in development environment all good. When I run `mix test` it compile the code in test environment. Where I'm getting the below error.

```elixir
warning: DateTimeUtilsMock is not included in any boundary
  deps/mox/lib/mox.ex:1
```

I'm having the module called `DateTimeUtils`. I need to mock it in my test case. So, I used `Mox` library to do the job.
For that, I configured module in `test/support/mocks.ex` file like `Mox.defmock(DateTimeUtilsMock, for: DateTimeUtils)`.

`DateTimeUtilsMock` module is created dynamically by `Mox`. Here, How I can add the boundary for the module which created dynamically?

**Comment by sasa1977** [comment]
My preferred strategy is to stash all test support modules under a single test boundary (e.g. `MySystemTest`), and ignore that boundary by defining the "root" module `MySystemTest` which is a boundary defined as `use Boundary, check: [in: false, out: false]`. Such boundary won't be checked for in or out calls. And now, you can define the mock module as `Mox.defmock(MySystemTest.DateTimeUtilsMock, for: DateTimeUtils)`.

This is briefly mentioned [here](https://hexdocs.pm/boundary/Boundary.html#module-controlling-checks).

**Comment by YasirAsar** [comment]
Thanks for the answer. For now, I modified the `mix.exs compilers` based on the environment. So, as per my new change `boundary` compiler not added in test environment.

```elixir
  defp custom_compilers() do
    if Mix.env() == :test, do: [], else:  [:boundary]
  end
```

If you see any loop holes in my solution, kindly help me with that.

**Comment by sasa1977** [comment]
This also works, but it will remove boundary integration from ElixirLS, so e.g. if you're using vscode, you won't see boundary warnings. This happens because ElixirLS compiles the project in test env.

**Comment by YasirAsar** [comment]
Okey, Thanks for the help. Then, I'll go with the suggested workaround
