### ISSUE TITLE
Double nesting not recognized

### ISSUE THREAD

**Issue by bfaganpapa** [sasa1977/boundary#55]
Hiya! Excited to use this in a big project.

Stripped-down example of double nesting:
```elixir
defmodule MySystem do
  use Boundary, top_level?: true, deps: [Nested]

  def hello do
    Nested.First.first()
    Nested.First.Second.second()
  end
end

defmodule Nested do
  use Boundary, top_level?: true, exports: :all

  defmodule First do
    use Boundary, exports: :all

    def first, do: "first"

    defmodule Second do
      use Boundary, exports: :all

      def second, do: "second"
    end
  end
end
```

But the Boundary compiler seems not to recognize that `Second` is exported all the way through to the top:
```bash
$ mix compile
Compiling 1 file (.ex)

warning: forbidden reference to Nested.First.Second
  (references from MySystem to Nested.First.Second are not allowed)
  lib/my_system.ex:6
  ```

I've tried a variety of techniques to get the export right, but it's never allowed. Is there something I'm missing here, or is double nesting maybe just not supported?

**Comment by bfaganpapa** [comment]
Ok, I have an amendment here. I realize that just exporting all the way down is not a recommended practice; I did this to show what I thought was a basic example of what's going on. Now I think there's something specifically either amiss with or that I'm not understanding about `exports: :all` and `exports: [{ModuleName, []}]`. As long as I stay away from using those in the `First` and `Second` modules as a way to export `Second` or `Second.Exported` beyond the `Nested` boundary, I'm ok.

This compiles as expected:
```elixir

defmodule MySystem do
  use Boundary, top_level?: true, deps: [Nested]

  def hello do
    Nested.First.first()
    Nested.First.Second.second()
    Nested.First.Second.Exported.exported()
  end
end

defmodule Nested do
  # This works with `exports: :all` as well
  use Boundary, top_level?: true, exports: [First, First.Second, First.Second.Exported]

  defmodule First do
    use Boundary, exports: [Second, Second.Exported]
    # Nope: use Boundary, exports: [Second, {Second, []}]
    # Nope: use Boundary, exports: :all

    def first, do: "first"

    defmodule Second do
      use Boundary, exports: [Exported]
      # Nope: use Boundary, exports: :all

      def second, do: "second"

      defmodule Exported do
        # Not a boundary; just a module in the `Second` subsubcontext
 
        def exported, do: "exported"
      end
    end
  end
end
```

So here are a few takeaways I have, in case they're helpful to others:
* Use explicit exports (vs `:all` or the tuple syntax) in sub-boundaries beyond the first level
* Make sure at any level that you're clearly differentiating between exporting functions in the context module and modules inside that context

I need to go with that for now, but if you all have an idea of what I'm running into here, and especially if it's my misunderstanding, I'd be happy to help by making a PR to update the docs once I understand.

**Comment by sasa1977** [comment]
Yeah, basically `:all` is currently not including stuff from sub-boundaries (except for the root module), and I'm not really sure if it should. We could perhaps add an opt to `:all` so we can e.g. do `exports: {:all, with: [Nested, AnotherNested]}`.

Another option is to not use sub-boundaries and make everything top-level. You can still model a hierarchy through a graph of deps. In your example `MySystem` would depend on `Nested` and `Nested.First`, and `Nested` would depend on `Nested.First` (all top-level boundaries).

TBH I'm starting to think wonder if this is better than nested boundaries. There are various special cases with sub-boundaries, as you can tell from the docs (e.g. the duality of the root module, dependency inheritance). OTOH top-level boundaries are IMO pretty straightforward. 

On the flip side, using fine-grained top-level boundaries in a larger project might lead to a lot of duplication, because you'd end up with a bunch of smaller boundaries that would all have to specify the same deps (instead of inheriting them through the common ancestor).

**Comment by bfaganpapa** [comment]
Thanks for your thoughtful response, Saša. I've been thinking through these OTOH issues you cover here a ton as I've worked to develop a proposal to establish Boundary usage in a large existing project (along the lines of [your suggestion in the docs](https://hexdocs.pm/boundary/Boundary.html#module-controlling-checks:~:text=easily%20achieve%20that.-,Another%20scenario,-is%20when%20introducing)). While I recognize that there's some logistical complexity involved in allowing deep boundary nesting, I'd hesitate for us to put an artificial limitation on people's domain boundary and encapsulation/modularity thinking. As you've noted in your series on _Maintainable Elixir_, contexts paired with Boundary enforcement can serve as a powerful mechanism to help folks recognize, name, bundle up, and distinguish business domains, application components, and even tools and infrastructure–and prepare them for thoughtful, explicit interactions. Complex monolithic applications do have big chunks that contain medium chunks that contain smaller, but still multi-module, chunks, so I'd advocate for finding a way for the Boundary specification mechanism to work the same at each level--so we can say and think that "it's contexts (and Boundaries) all the way down."

I'll close this as not really an issue as much as logistical details conversation, but if you'd like to chat further or for me to think through how we could clarify this subtlety in the docs, I'm happy to help. Thanks again for the chat and for your work on Boundary and throughout the Elixir community.
