### ISSUE TITLE
Incremental compilation x dirty_xrefs = false positives

### ISSUE THREAD

**Issue by PragTob** [sasa1977/boundary#56]
Hi there Saša,

first of all - thanks for the library it's great! 💚  Also, thanks for the recent release and the inclusion of `dirty_xrefs`. We're still looking at a wider adoption of boundary and that is certainly an exciting feature - both the way to basically push violations to the caller and to warn if they are no longer needed 🌟 

I always assumed/told people that as a compiler boundary works with incremental compilation. However, recently I found that not to be the case. TLDR; of the log below is that switching from some point to a branch that introduces a new boundary with `dirty_xrefs` produces a lot of false positive warnings of "this dirty_xref is not needed" as shown by them disappearing on a full forced compile:

<details>
<summary>False positives switching back and forth on compile</summary>

```
➜  project git:(domain-example-4) ✗ git checkout e846fc39
➜  project git:(e846fc3980a) ✗ MIX_ENV=test COMPILE_BOUNDARY=true mix compile
Compiling 934 files (.ex)
Compiling lib/project_web/router.ex (it's taking more than 10s)
Generated project app
➜  project git:(e846fc3980a) ✗ git checkout domain-example-4
Switched to branch 'domain-example-4'
Your branch is up to date with 'origin/domain-example-4'.
➜  project git:(domain-example-4) ✗ MIX_ENV=test COMPILE_BOUNDARY=true mix compile
Compiling 930 files (.ex)
Compiling lib/project_web/router.ex (it's taking more than 10s)
Generated project app

warning: module Project.Domain.Handlers.Domain doesn't need to be included in the `dirty_xrefs` list for the boundary Other
  lib/Other.ex:6

warning: module Project.Domain.FactSchema doesn't need to be included in the `dirty_xrefs` list for the boundary OtherWeb
  lib/Other_web.ex:12

warning: module Project.Domain.CoreBenefit doesn't need to be included in the `dirty_xrefs` list for the boundary Project
  lib/project.ex:12

warning: module Project.Domain.EmployerContribution doesn't need to be included in the `dirty_xrefs` list for the boundary Project
  lib/project.ex:12

warning: module Project.Domain.FactReference doesn't need to be included in the `dirty_xrefs` list for the boundary Project
  lib/project.ex:12

warning: module Project.Domain.FactSchema doesn't need to be included in the `dirty_xrefs` list for the boundary Project
  lib/project.ex:12

warning: module Project.Domain.Finder.ListCoreBenefits doesn't need to be included in the `dirty_xrefs` list for the boundary Project
  lib/project.ex:12

warning: module Project.Domain.Finder.ListRegions doesn't need to be included in the `dirty_xrefs` list for the boundary Project
  lib/project.ex:12

warning: module Project.Domain.Handlers.Fact doesn't need to be included in the `dirty_xrefs` list for the boundary Project
  lib/project.ex:12

warning: module Project.Domain.Handlers.Domain doesn't need to be included in the `dirty_xrefs` list for the boundary Project
  lib/project.ex:12

warning: module Project.Domain.DomainEnums doesn't need to be included in the `dirty_xrefs` list for the boundary Project
  lib/project.ex:12

warning: module Project.Domain.Region doesn't need to be included in the `dirty_xrefs` list for the boundary Project
  lib/project.ex:12

warning: module Project.Domain.Services.ResolveFactReferences doesn't need to be included in the `dirty_xrefs` list for the boundary Project
  lib/project.ex:12

warning: module Project.Domain.TimeoffPolicy doesn't need to be included in the `dirty_xrefs` list for the boundary Project
  lib/project.ex:12

warning: module Project.Domain.TimeoffPolicy.Carryover doesn't need to be included in the `dirty_xrefs` list for the boundary Project
  lib/project.ex:12

warning: module Project.Domain.TimeoffPolicy.ProRatingRule doesn't need to be included in the `dirty_xrefs` list for the boundary Project
  lib/project.ex:12

warning: module Project.Domain.Value.Region doesn't need to be included in the `dirty_xrefs` list for the boundary Project
  lib/project.ex:12

warning: module Project.Domain.DomainEnums doesn't need to be included in the `dirty_xrefs` list for the boundary ProjectWeb
  lib/project_web.ex:20

➜  project git:(domain-example-4) ✗ MIX_ENV=test COMPILE_BOUNDARY=true mix compile --force
Compiling 7192 files (.ex)
Generated project app
```

</details>

My expectation would be for these false positives not to be reported/no warnings should be presented after switching to the branch - just like in a full compile. So, question is - is this a bug or is it not supposed to work with incremental compilation? Did I do something wrong (I don't think/hope so - I even shut down vscode to keep the language server from interfering)?

I haven't put in the work yet to create a minimal reproduction example but if needed I can see if I can wip one up.

I also just double checked, and elixir/erlang versions (1.15.4 on OTP 25.3.2.5) as well as boundary versions (0.10.0) are the same between the 2 branches (the commit entry point is arbitrary/the one where I first noticed the issues):

<details>
<summary>Version information on branches</summary>

```
➜  project git:(e846fc3980a) ✗ mix deps | grep boundary
* boundary 0.10.0 (Hex package) (mix)
  locked at 0.10.0 (boundary) c78eee15
➜  project git:(e846fc3980a) ✗ elixir -v
Erlang/OTP 25 [erts-13.2.2.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.15.4 (compiled with Erlang/OTP 25)
➜  project git:(e846fc3980a) ✗ git checkout domain-example-4
Your branch is up to date with 'origin/domain-example-4'.
➜  project git:(domain-example-4) ✗ mix deps | grep boundary
* boundary 0.10.0 (Hex package) (mix)
  locked at 0.10.0 (boundary) c78eee15
➜  project git:(domain-example-4) ✗ elixir -v
Erlang/OTP 25 [erts-13.2.2.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.15.4 (compiled with Erlang/OTP 25)
```
</details>

**Comment by sasa1977** [comment]
Boundary should work with incremental recompilation, if by that you mean the situation where only the changed files (and their compile-time deps) are compiled.

The basic flow is:

1. Boundary keeps the database of cross-module calls. This is basically a bag ETS, where the key is the module, while the value holds the call details.
2. Whenever a module is recompiled, the entries for that module are deleted.
3. After the Elixir compiler is done, boundary analyzes the full-state of the world, i.e. all function calls, not just the ones in the recompiled modules.

Off the top of my head I can't think of how this would fail with branch switching, and I didn't experience it in practice (the feature has been used in a large real-life project). But clearly you have an issue, so something is off. Unfortunately, without a repro repo I don't have much to go on with.

**Comment by PragTob** [comment]
I see, thanks for the quick answer Saša! I'll see if I can recreate it in a smaller repo I can share, but yeah all the files changed will be tough to get done 😅 

It can reliably be reproduced here.

I'll let you know once we have something, thanks!

**Comment by Nezteb** [comment]
@PragTob Out of curiosity, did you end up figuring out how to reproduce this?

**Comment by PragTob** [comment]
@Nezteb no I didn't, I also left Remote about a month after writing that message so I don't have access any more and while it was on my TODO list I didn't get it done in those stressful weeks. Thanks for the ping!

@sasa1977 since I can't reproduce and no one else from Remote seems to have followed up here I'll close it, as without a reproduction case I don't think anything can be done here and I don't think such a thing will be coming. Thank you for all your work!
