### ISSUE TITLE
Unexpected compiler warning after upgrade to 0.10.1

### ISSUE THREAD

**Issue by beerlington** [sasa1977/boundary#60]
Hi,

I'm upgrading my production application from 0.9.4 to 0.10.1 and am seeing a new warning that I'm not expecting. I'm able to reproduce it pretty easily and have narrowed it down to using `@derive Jason.Encoder` in a struct.

The warning is:

```
warning: Jason.Encoder.TestApp.MyStruct is not included in any boundary
  lib/test_app/my_struct.ex:1
```

The file it's referring to is just `TestApp.MyStruct`, but uses `@derive Jason.Encoder`, so I'm not sure why it adds the `Jason.Encoder` prefix in the warning.

You should be able to reproduce the issue following these steps:

1. Download my test app from https://github.com/beerlington/boundary-issue
2. Run `mix deps.get`
3. Run `mix test` and confirm there is no error
4. Check out the [`upgrade-0.10.1`](https://github.com/beerlington/boundary-issue/pull/1) branch that updates the version
5. Run `mix deps.get`
6. Run `mix test` and you should see the error I posted above.

I should also note that I only see this warning once and that it seems to resolve itself, possibly after the struct module is recompiled.

I'm using Elixir 1.15.2 and OTP 25.

**Comment by sasa1977** [comment]
Yeah, this sounds like a duplicate of #58. Basically, due to some changes in the internals, after you upgrade to the latest boundary, you should do a one-off invocation of `mix compile --force` (in dev and test).

**Comment by beerlington** [comment]
Ah yes, you're correct, this looks like the exact same issue. Thanks!
