### ISSUE TITLE
Wrong positive after 1.10.2 with incremental recompilation

### ISSUE THREAD

**Issue by Miradorn** [sasa1977/boundary#64]
Hey and thanks for the library and all the work!

I think a bug might have snug into the latest version.

We're using `Mox` to implicitly define modules for tests, before we had them explicitly as part of a boundary, with the upgrade we did remove them (as expected).

This works great for the first run of `mix compile` but any subsequent incremental runs will fail with the mock modules being reported as not exported by its boundary.

reproduction steps:

run `MIX_ENV=test COMPILE_BOUNDARY=true mix compile --force --warnings-as-errors` , which succeeds, and directly after without any changes do `MIX_ENV=test COMPILE_BOUNDARY=true mix compile --warnings-as-errors` which fails.

**Comment by sasa1977** [comment]
Thanks for the report. Do you have a link to the repo?

**Comment by Miradorn** [comment]
sorry, it's the private one from work Xx. I can try to setup a reproduction if I have time today 🙈

**Comment by Miradorn** [comment]
here you go: https://github.com/Miradorn/boundary_example
Step 1: `MIX_ENV=test mix compile --force` -> suceeds
Step 2: `MIX_ENV=test mix compile` fails

**Comment by sasa1977** [comment]
Pushed the fix to master. Would you mind giving it a try on the real project, before I push the new version?

**Comment by Miradorn** [comment]
thanks, works beautifully!

**Comment by sasa1977** [comment]
Pushed 0.10.3 to hex.
