### ISSUE TITLE
replace xref with compilation tracers

### ISSUE THREAD

**Issue by sasa1977** [sasa1977/boundary#7]
Currently, we're using [xref](https://hexdocs.pm/mix/Mix.Tasks.Xref.html#calls/1) to collect cross-module references. As @josevalim mentioned in [this comment](https://github.com/elixir-lang/elixir/issues/9322#issuecomment-526926533), starting from Elixir 1.10, it will be more efficient to do this with [compilation tracers](https://hexdocs.pm/elixir/master/Code.html#module-compilation-tracers).

Therefore, it seems that we should base boundaries on top of Elixir `~> 1.10` and use compilation tracers to collect cross-module references.

Looking at the current docs, I'm not completely clear how the usage & the solution would look like. It seems that the client code would have to specify the boundary tracer via
`elixirc_options: [tracers: [Boundary]]`, and then also add the boundary compiler, as it's already done today. The tracer would first collect the xref data, which would then be available to the compiler.

The docs don't seem to go into details of how the tracer should collect the data, but there is a passing suggestion that most of the work should be done asynchronously in other processes. So, one idea which immediately comes to mind is to start up a singleton (i.e. locally registered) process during compilation and stuff the data there (maybe using public named ETS for better throughput). 

However, I'm not sure what happens on recompilation. Suppose I compile a project, and then make a small change which requires recompilation of only one file. I'd expect that in this case we'd receive traces only for that file. If that's correct, it seems we need to persist the data on the disk.

@josevalim could you provide some insight on the following questions:

1. If we're using tracers, the user will have to configure the tracer and the compiler in mix.exs?
2. Collecting data can be done in some singleton BEAM resource (process, ets table)?
3. Do we need to persist this data locally somewhere, to properly handle partial compilations?

**Comment by josevalim** [comment]
Yes, yes and yes.

The last disclaimer is that tracers also run during tests but you can
remove them when you run your compiler pass. I actually have an idea to
simplify things, I will try it out and let you know.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
So I have just added Mix.Task.Compiler.after_compile, so you can have a
compiler at the front that will add the tracer and you register a function
that will be invoked at the end to generate the warnings. Just remember to
remove the tracer on the function callback.

**Comment by sasa1977** [comment]
Cool, thanks!

**Comment by sasa1977** [comment]
@josevalim I just started playing with this, and bumped into an issue. Since the tracer module has to be compiled, it follows that it can't be a part of the same project, but in fact it has to be in a dependency, right?

I'm asking, because currently boundary also checks itself. If I still want to retain this behaviour (which I do, because I also rely on it during tests), my only option is to extract the tracing collection into a separate project, right?

**Comment by josevalim** [comment]
@sasa1977 if the concern is testing, you can compile your test fixtures in a separate step by calling `Kernel.ParallelCompiler`. If necessary, output the beams to a separate directory which you add to the load path. That's what Elixir does to test .beam files, since we have similar bootstrapping concerns.

**Comment by sasa1977** [comment]
Thanks! I also established that I can define the tracer module in `mix.exs`. Not sure if it's the best approach, but it looks like an easy way out :-D It basically means that I can configure the tracer in boundary `mix.exs` and it will always be invoked. WDYT?

**Comment by josevalim** [comment]
That is not going to work when others use boundary as a dependency though?

**Comment by sasa1977** [comment]
> That is not going to work when others use boundary as a dependency though?

Experimentally it seems to be working at least in a simple case (`boundary` is a direct path-based dep), but after playing a bit more, I've decided to use this approach only inside the `boundary` lib, using a classical compiler for client projects. Thanks for the tips!
